In [1]:
import pandas as pd
# Read powerplants.csv file

powerplants_df = pd.read_csv('powerplants.csv')

# display first 5 rows of the dataframe
powerplants_df.head()

,id,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,0,Pumpspeicherkraftwerk Erzhausen,Hydro,Pumped Storage,Storage,Germany,200.0,0.75,1964.0,1998.0,NaN,51.898566,9.924887,5.510000,1.600000,287.0,1102.0,{nan},"{'MASTR': {'MASTR-SEE915985628661'}, 'GEM': {'..."
1,1,La Plate Taille,Hydro,Pumped Storage,Store,Belgium,144.0,NaN,1970.0,NaN,NaN,50.188400,4.386200,4.930556,68.400000,70.0,710.0,{nan},"{'GEM': {'G100000600151'}, 'JRC': {'JRC-H347'}..."
2,2,Illwerke Vkw Rodundwerk,Hydro,Reservoir,Store,Austria,495.0,0.75,1943.0,2011.0,NaN,47.085032,9.880116,588.383838,2.240000,353.0,291250.0,"{nan, nan, nan, nan, nan}","{'MASTR': {'MASTR-SEE952262880046', 'MASTR-SEE..."
3,3,Bissorte,Hydro,Pumped Storage,Store,France,818.0,NaN,1936.0,NaN,NaN,45.203600,6.581450,3.818182,39.500000,1160.0,3150.0,"{nan, nan}","{'GEM': {'G100001052026', 'G100000601707'}, 'J..."
4,4,Obervermuntwerk Maschine Turbine,Hydro,Pumped Storage,Storage,Austria,380.0,0.75,1943.0,2018.0,NaN,46.935290,10.059950,71.573684,35.630769,291.0,27198.0,"{nan, nan}","{'MASTR': {'MASTR-SEE926367113644', 'MASTR-SEE..."

In [2]:
# Find power plants in Denmark only
dk_all_power = powerplants_df[powerplants_df['Country'] == 'Denmark']

# Include plants active in 2025 or with no known decommissioning date
dk_all_power = dk_all_power[
    (dk_all_power['DateOut'] >= 2025) |
    (dk_all_power['DateOut'].isna())
]

dk_all_power

,id,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
555,555,Nordjylland,Hard Coal,Steam Turbine,CHP,Denmark,716.00,NaN,1976.0,1998.0,2028.0,57.073694,10.040779,NaN,NaN,NaN,NaN,"{nan, nan}","{'GEM': {'G100000107495', 'G100000107496'}, 'E..."
960,960,Herning,Solid Biomass,Steam Turbine,CHP,Denmark,80.00,NaN,1982.0,2008.0,NaN,56.121400,9.006800,NaN,NaN,NaN,NaN,{nan},"{'GEM': {'G100000200229'}, 'GPD': {'WRI1022044..."
1915,1915,Randers,Solid Biomass,NaN,CHP,Denmark,52.00,NaN,1982.0,2002.0,NaN,56.457900,10.046600,NaN,NaN,NaN,NaN,{nan},"{'GEM': {'G100000202506'}, 'GPD': {'WRI1022042..."
2373,2373,Orsted,Natural Gas,Steam Turbine,CHP,Denmark,338.00,NaN,1985.0,2004.0,2025.0,55.654741,12.549117,NaN,NaN,NaN,NaN,"{nan, nan, nan}","{'GEM': {'G100001030699', 'G100000400070', 'G1..."
2563,2563,Avedore,Solid Biomass,NaN,PP,Denmark,835.00,NaN,1990.0,2002.0,NaN,55.602160,12.479064,NaN,NaN,NaN,NaN,"{nan, nan}","{'GEM': {'G100000202505', 'G100000201362'}, 'E..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25916,25920,Porkeri Wind Plus,Battery,Li,Store,Denmark,6.00,NaN,NaN,NaN,NaN,61.490000,-6.780000,NaN,NaN,NaN,7.45,{nan},{'EESI': {'EESI-63053'}}
25924,25928,Primolyzer,Hydrogen Storage,NaN,Store,Denmark,0.01,NaN,NaN,NaN,NaN,56.263900,9.501800,NaN,NaN,NaN,NaN,{nan},{'EESI': {'EESI-65078'}}
25947,25951,Riso Syslab Redox Flow,Battery,V,Store,Denmark,0.02,NaN,NaN,NaN,NaN,55.784638,12.504610,NaN,NaN,NaN,0.12,{nan},{'EESI': {'EESI-61718'}}
25999,26003,Suduroy Bess,Battery,Li,Store,Denmark,6.00,NaN,NaN,NaN,NaN,55.670249,10.333328,NaN,NaN,NaN,7.50,{nan},{'EESI': {'EESI-63898'}}
26055,26059,Vestenskov Nakskov Industrial Environmental Pa...,Hydrogen Storage,NaN,Store,Denmark,0.08,NaN,NaN,NaN,NaN,54.833300,11.133300,NaN,NaN,NaN,NaN,{nan},{'EESI': {'EESI-65080'}}

In [6]:
# List all fuel types in dk_all_power
print(dk_all_power['Fueltype'].unique())
print(dk_all_power['Technology'].unique())
print(dk_all_power['Efficiency'].unique())

['Hard Coal' 'Solid Biomass' 'Natural Gas' 'Oil' 'Solar' 'Wind' 'Waste'
 'Battery' 'Hydrogen Storage' 'Heat Storage']
['Steam Turbine' nan 'CCGT' 'PV' 'Offshore' 'Csp' 'Onshore' 'Li'
 'Molten Salt' 'V']
[nan]

In [4]:
dk_conv_power = dk_all_power[
    (dk_all_power['Fueltype'] == 'Hard Coal') |
    (dk_all_power['Fueltype'] == 'Solid Biomass') |
    (dk_all_power['Fueltype'] == 'Natural Gas') |
    (dk_all_power['Fueltype'] == 'Oil') |
    (dk_all_power['Fueltype'] == 'Waste')
]

dk_ren_power = dk_all_power[
    (dk_all_power['Fueltype'] == 'Wind') |
    (dk_all_power['Fueltype'] == 'Solar')
]

In [5]:

print(f"Total Installed Capacities in Denmark 2025", dk_all_power['Capacity'].sum(), 'MW')


print(f'Hard Coal, Solid Biomass, Natural Gas, Oil and Waste Capacities Installed in Denmark 2025:', dk_conv_power['Capacity'].sum(), "MW")


print(f'Wind and Solar Capacities Installed in Denmark 2025', dk_ren_power['Capacity'].sum(), "MW")

Total Installed Capacities in Denmark 2025 12419.9 MW
Hard Coal, Solid Biomass, Natural Gas, Oil and Waste Capacities Installed in Denmark 2025: 4289.2 MW
Wind and Solar Capacities Installed in Denmark 2025 8073.200000000001 MW